seed: 42
input_dir: /workspace/ranking_loss/data
use_wandb: true


model:
  backbone_path: microsoft/deberta-v3-base
  gradient_checkpointing: true
  dropout_rate: 0.05
  max_length: 1024


train:
  gradient_accumulation_steps: 2
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  num_train_epochs: 3
  warmup_pct: 0.02
  eval_frequency: 100
  no_improvement_threshold: 10
  max_grad_norm: 1.0


optimizer:
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  
  head_lr: 2e-5
  lr: 2e-5
  weight_decay: 1e-3
  max_grad_norm: 1.0


  use_bnb: false
  use_llrd: true 
  llrd: 0.9 

output:
  dir: /workspace/ranking_loss/rank_results
  name: ranking


